package com.telusko.quizApp.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

//we want this table to be mapped with the class thus we use @Entity
//if u have a different table name u need to use @Table
//we're using lambok thus no need to create getters adn setters thus we use @Data coming from lombok for that
@Data
@Entity
public class Question
{
//    think of a class design matching the table design thus class name= table name, class fields= table columns
//    the number of objects in a class, each object= row  (ORM=object relational mapping)
//    match the variable name here with the column name in the table

//    we need to make sure the Integer is a primary key thus how we do that is mention the Id as an annotation
    @Id
//    we also need it to be autogenerated, thus use generationType  identity
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
//    below in our database the questionTitle has a underscore but here we write it without but second word must start with a capital.The springboot will take care of it
    private String questionTitle;
    private String option1;
    private String option2;
    private String option3;
    private String option4;
    private String rightAnswer;
//    now we work for difficulty level. In database difficultylevel doesn't have an underscore thus we dont start second word with capital
    private String difficulty_level;
    private String category;

}
